#### arange 함수
##### numpy.arange(start, stop, step, dtype=None)
- start: 시작 값, 범위에 포함, default = 0
- stop: 종료 값, 범위에 포함X
- step: 값 사이의 간격, default = 1
- dtype: 생성된 배열의 데이터 유형을 지정, default = 입력 값에 따라 자동으로 결정됩니다.


In [4]:
import numpy as np

# start, stop, step 지정
arr2 = np.arange(2, 10, 2)
print(arr2)

# 부동 소수점 사용
arr3 = np.arange(0, 1, 0.1)
print(arr3)

# dtype 지정
arr4 = np.arange(1, 6, dtype = float)
print(arr4)

[2 4 6 8]
[0.  0.1 0.2 0.3 0.4 0.5 0.6 0.7 0.8 0.9]
[1. 2. 3. 4. 5.]


#### random 함수



In [ ]:
# random.rand 함수 : (0, 1) 범위에서 균일한 분포를 가지는 난수를 생성 
# numpy.random.rand(d0, d1, ..., dn)

np.random.rand(5).round(3)
np.random.rand(5, 3).round(3)

# random.normal 함수 : 정규 분포를 따르는 난수 생성
# numpy.random.normal(loc=0.0, scale=1.0, size=None)
# loc: 정규 분포의 평균 값, default = 0.0
# scale: 정규 분포의 표준 편차 값, default = 1.0
# size: 생성하려는 배열의 형상(shape), default = None

np.random.normal(loc = 1.0, scale = 1.0, size = (2, 3))

#### linspace 함수
##### numpy.linspace(start, stop, num=50, endpoint=True, retstep=False, dtype=None)
- start: 시작 값, 범위에 포함
- stop: 종료 값, 범위에 포함X
- num: 생성하려는 값의 개수, default = 50
- endpoint: 종료 값이 결과에 포함되는지 여부, default = True
- retstep: 간격(step) 값을 함께 반환할지 여부, default = False
- dtype: 생성된 배열의 데이터 유형, default = 입력 값에 따라 자동으로 결정


In [ ]:
# 기본 사용법
arr1 = np.linspace(0, 1, num=5)
print(arr1)

# 개수와 간격 확인
arr2, step = np.linspace(0, 1, num=5, retstep=True)
print(arr2)
print(step)

# 종료 값 포함하지 않음
arr3 = np.linspace(0, 10, num=5, endpoint=False)
print(arr3)

# 데이터 유형 지정
arr4 = np.linspace(1, 5, num=5, dtype=np.integer)
print(arr4)



#### 배열 인덱싱 및 슬라이싱

In [7]:
arr = np.array([1, 2, 3, 4, 5])
idx = np.array([0, 2, 4])

# 인덱스 배열에 해당하는 요소만 선택
print(arr[idx])  # [1 3 5]

[1 3 5]
